AWSTemplateFormatVersion: '2010-09-09'
Description: Create s3-empty-bucket lambda
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:ListBucketVersions
            Resource: arn:aws:s3:::*
          - Effect: Allow
            Action:
            - s3:DeleteObject
            - s3:DeleteObjectVersion
            Resource: arn:aws:s3:::*/*
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: showaltb-rhs
        S3Key: 1df8cd9b857ede3bfe85e5d0f7329d22
      Description: Empty an S3 bucket
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - Role
        - Arn
      Runtime: nodejs12.x
      Timeout: 300
